### PR TITLE
Update polars to 0.41.3

### PR DESCRIPTION
**Pull request by DongzeHE**

### CODE REVIEW

**Comment by rob-p** [comment]
@DongzeHE : Do we mean 0.41.0? rather than 0.14.0?

**Comment by DongzeHE** [comment]
I think github will update the version for us?

**Comment by rob-p** [comment]
I mean in the name of this PR.  The latest version is 0.41.3 (https://docs.rs/polars/latest/polars/) — I think we should make sure we are pulling that in :).

**Comment by rob-p** [comment]
We are talking about 2 different things, I think ;P.  The Polars version (being referred in the name of this PR) is 0.41.3 (you are using that). When we merge back into main, this will bump grangers to 0.4.1 (or 0.5.0 if there are more than just patch changes), right?

**Comment by DongzeHE** [comment]
My fault! the name of the PR was wrong. The version of polars used in this PR is the latest.

**Pull request merged**
